apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/image-list: vigilant-engine=ghcr.io/shipperizer/vigilant-engine
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/repo-953774906
    argocd-image-updater.argoproj.io/vigilant-engine.pull-secret: pullsecret:argocd/regcred-github
    argocd-image-updater.argoproj.io/vigilant-engine.kustomize.image-name: ghcr.io/shipperizer/vigilant-engine
    argocd-image-updater.argoproj.io/vigilant-engine.allow-tags: regexp:^v[0-9]+.[0-9]+.*
  name: vigilant-engine
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: deployments/kustomize
    repoURL: git@github.com:shipperizer/vigilant-engine.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
