apiVersion: skaffold/v2beta11
kind: Config
build:
  artifacts:
  - image: ghcr.io/shipperizer/vigilant-engine
    sync:
      infer:
      - "cmd/app/main.go"
      - "go.mod"
      - "go.sum"
    custom:
      buildCommand: ./buildx.sh
      dependencies:
        dockerfile:
          path: Dockerfile
          buildArgs:
            app_name: app

deploy:
  kubectl:
    manifests:
    - "argocd.yaml"
  kustomize:
    paths:
      - "deployments/kustomize"

profiles:
- name: cert-manager
  patches:
    - op: remove
      path: /deploy/kustomize
  deploy:
    kubectl:
      manifests:
        - "deployments/deps/cert-manager/*.yaml"
- name: kaniko
  build:
    artifacts:
    - image: ghcr.io/shipperizer/vigilant-engine
      kaniko:
        image: gcr.io/kaniko-project/executor:arm64
        initImage: docker.io/busybox:stable
        buildArgs:
          TARGETOS: linux
          TARGETARCH: arm64
    cluster:
      randomDockerConfigSecret: true
      dockerConfig:
        secretName: regcred-github-kaniko
