apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  deployment: vigilant-engine
  app: vigilant-engine

resources:
- deployment.yaml
- configMap.yaml

images:
- name: ghcr.io/shipperizer/vigilant-engine
  newTag: v1.0.0
